### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by tuxedotje** [2nv2u/gnome-shell-extension-syncthing-indicator#10]
Error message after update.
I did Remove  extension, and reinstall but that does does nothing. Not a new install  extension in .local/share/shell  ... extensions

**Comment by 2nv2u** [comment]
Can you elaborate a bit more? I don't see this problem happening in both a clean install of Ubuntu and Fedora

**Comment by tuxedotje** [comment]
I did remove the files in  ~/.local/share/gnome-shell/extensions
Install from https://extensions.gnome.org/  
There it has the ERROR button. in https://extensions.gnome.org/local/
I will try a fresh boot after remove and install after reboot.

**Comment by tuxedotje** [comment]
Did remove dir from /.local/share/gnome-shell/extensions
reboot
install from https://extensions.gnome.org
Now it is OK 
It was the reboot??

**Comment by 2nv2u** [comment]
I cannot tell what went wrong, it would be just guessing, I'm happy you managed to get it working again though.
Gnome Shell can be flaky when it comes to extensions, do let me know when you run into something else though.
