### ISSUE TITLE
Constant Syncthing Indicator Daemon Error: Service Failed to Start

### ISSUE THREAD

**Issue by nebhead** [2nv2u/gnome-shell-extension-syncthing-indicator#11]
The service is running, which I can access via my browser, but I'm wondering if it's because I have it password protected that the indicator daemon cannot access it?

**Comment by 2nv2u** [comment]
It's probably because the service can't be started in user space and is already running at system level, I'll see if I can suppress the message and disable the switch if this is detected, stay tuned

**Comment by 2nv2u** [comment]
Probably not, even if I would just leave the systemd controls disabled the config is most likely not located in your user folder, the indicator currently checks for it there to determine how to connect to the daemon.
If you can think of a solid way to determine any other locations for it I'll be happy to look into it to help you out.

**Comment by nebhead** [comment]
> Probably not, even if I would just leave the systemd controls disabled the config is most likely not located in your user folder, the indicator currently checks for it there to determine how to connect to the daemon. 

Ah... got it.  OK.  I can't offer any clever solutions on this one unfortunately. 

> edit: The passwords shouldn't be a problem, it uses the API key

Great.  OK.  So perhaps I need remove my current install and then enable this method instead.  Thanks!  I will got ahead and close this issue.  Thanks again for looking into it.
