### ISSUE TITLE
Syncthing-indicator log messages

### ISSUE THREAD

**Issue by PhilippeRo** [2nv2u/gnome-shell-extension-syncthing-indicator#12]
Hi,
first, thanks for your extension. It's great.
I wanted to report some error messages that appear in journalctl (see attached). I should add that the extension keeps working despite theses messages.
[log.txt](https://github.com/2nv2u/gnome-shell-extension-syncthing-indicator/files/7611679/log.txt)
I can't tell what triggers them.
I use gnome 41 & fedora 35.
Let me know if you need any information.

**Comment by 2nv2u** [comment]
I removed deprecated code which might have caused this, please check if it's still there

**Comment by PhilippeRo** [comment]
Sorry, I'm still seeing the same error messages as before (5 times today in the logs) with the new version.

**Comment by 2nv2u** [comment]
Can you send me the line locations again? (Just those 8 lines)

**Comment by PhilippeRo** [comment]
Here you go.
[log.txt](https://github.com/2nv2u/gnome-shell-extension-syncthing-indicator/files/7635775/log.txt)
Note that there are two different stack traces to lead to two different lines and that both are repeated several times.
Thanks

**Comment by 2nv2u** [comment]
Sorry for the late response, I cannot seem to reproduce this, are you doing something specific or does it just happen?

**Comment by PhilippeRo** [comment]
I do still see the errors in the log. I've moved on to fedora 36 andthe log is the following :mars 31 18:29:35 genesyme-home gnome-shell[4738]: == Stack trace forcontext 0x55779b92e620 ==mars 31 18:29:35 genesyme-home gnome-shell[4738]: #0 5577a38c74a0 i ***@***.***/extension.js:232 (3ac45e999560 @ 12)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #1 7ffe6c5a8ad0 b resource:///org/gnome/gjs/modules/core/_signals.js:114 (3cdb913d3920 @433)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #2 7ffe6c5a8bd0 b ***@***.***/syncthing.js:155 (3ac45e99a560 @ 27)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #3 7ffe6c5a9300 b ***@***.***/syncthing.js:182 (3ac45e99a6a0 @ 71)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #4 7ffe6c5a9960 b ***@***.***/syncthing.js:186 (3ac45e99a6f0 @ 20)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #5 7ffe6c5a9a40 b ***@***.***/syncthing.js:201 (3ac45e99a7e0 @ 68)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #6 5577a38c7358 i ***@***.***/syncthing.js:185 (3ac45e99a6a0 @ 134)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #7 5577a38c72b8 i ***@***.***/syncthing.js:803 (3ac45e99e920 @ 130)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #8 5577a38c7230 i ***@***.***/extension.js:549 (3ac45e99a060 @ 53)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #9 5577a38c7160 i resource:///org/gnome/shell/ui/extensionSystem.js:122 (2970cc4d290 @386)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #10 5577a38c70d8 iresource:///org/gnome/shell/ui/extensionSystem.js:514 (2970cc4da60 @15)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #11 7ffe6c5aa530 bself-hosted:205 (3cdb913bed80 @ 272)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #12 5577a38c7050 iresource:///org/gnome/shell/ui/extensionSystem.js:514 (2970cc4d920 @120)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #13 5577a38c6fc8 iresource:///org/gnome/shell/ui/extensionSystem.js:636 (2970cc4dec0 @17)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #14 7ffe6c5aafa0 bself-hosted:1181 (3cdb913b0a10 @ 423)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #15 7ffe6c5ab0a0 bresource:///org/gnome/gjs/modules/core/_signals.js:114 (3cdb913d3920 @433)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #16 7ffe6c5abc40 bresource:///org/gnome/shell/ui/sessionMode.js:199 (c704ddc5970 @ 283)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #17 5577a38c6d80 iresource:///org/gnome/shell/ui/sessionMode.js:160 (c704ddc5830 @ 40)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #18 5577a38c6cd0 iresource:///org/gnome/shell/ui/screenShield.js:612 (c704ddbb150 @ 206)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #19 5577a38c6c40 iresource:///org/gnome/shell/ui/screenShield.js:333 (c704ddb9920 @ 36)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #20 7ffe6c5ac7e0 bself-hosted:1181 (3cdb913b0a10 @ 454)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #21 5577a38c6bb8 iresource:///org/gnome/shell/ui/lightbox.js:198 (2970cc306f0 @ 29)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #22 5577a38c6b30 iresource:///org/gnome/shell/ui/environment.js:134 (3cdb913cc4c0 @ 98)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #23 5577a38c6aa8 iresource:///org/gnome/shell/ui/environment.js:221 (3cdb913cc830 @ 14)mars 31 18:29:35 genesyme-home gnome-shell[4738]: == Stack trace forcontext 0x55779b92e620 ==mars 31 18:29:35 genesyme-home gnome-shell[4738]: #0 5577a38c74a0 i ***@***.***/extension.js:232 (3ac45e999560 @ 12)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #1 7ffe6c5a96f0 b resource:///org/gnome/gjs/modules/core/_signals.js:114 (3cdb913d3920 @433)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #2 7ffe6c5a97f0 b ***@***.***/syncthing.js:155 (3ac45e99a560 @ 27)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #3 7ffe6c5a98a0 b ***@***.***/syncthing.js:182 (3ac45e99a6a0 @ 71)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #4 7ffe6c5a9960 b ***@***.***/syncthing.js:186 (3ac45e99a6f0 @ 20)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #5 7ffe6c5a9a40 b ***@***.***/syncthing.js:201 (3ac45e99a7e0 @ 68)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #6 5577a38c7358 i ***@***.***/syncthing.js:185 (3ac45e99a6a0 @ 134)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #7 5577a38c72b8 i ***@***.***/syncthing.js:803 (3ac45e99e920 @ 130)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #8 5577a38c7230 i ***@***.***/extension.js:549 (3ac45e99a060 @ 53)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #9 5577a38c7160 i resource:///org/gnome/shell/ui/extensionSystem.js:122 (2970cc4d290 @386)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #10 5577a38c70d8 iresource:///org/gnome/shell/ui/extensionSystem.js:514 (2970cc4da60 @15)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #11 7ffe6c5aa530 bself-hosted:205 (3cdb913bed80 @ 272)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #12 5577a38c7050 iresource:///org/gnome/shell/ui/extensionSystem.js:514 (2970cc4d920 @120)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #13 5577a38c6fc8 iresource:///org/gnome/shell/ui/extensionSystem.js:636 (2970cc4dec0 @17)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #14 7ffe6c5aafa0 bself-hosted:1181 (3cdb913b0a10 @ 423)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #15 7ffe6c5ab0a0 bresource:///org/gnome/gjs/modules/core/_signals.js:114 (3cdb913d3920 @433)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #16 7ffe6c5abc40 bresource:///org/gnome/shell/ui/sessionMode.js:199 (c704ddc5970 @ 283)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #17 5577a38c6d80 iresource:///org/gnome/shell/ui/sessionMode.js:160 (c704ddc5830 @ 40)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #18 5577a38c6cd0 iresource:///org/gnome/shell/ui/screenShield.js:612 (c704ddbb150 @ 206)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #19 5577a38c6c40 iresource:///org/gnome/shell/ui/screenShield.js:333 (c704ddb9920 @ 36)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #20 7ffe6c5ac7e0 bself-hosted:1181 (3cdb913b0a10 @ 454)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #21 5577a38c6bb8 iresource:///org/gnome/shell/ui/lightbox.js:198 (2970cc306f0 @ 29)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #22 5577a38c6b30 iresource:///org/gnome/shell/ui/environment.js:134 (3cdb913cc4c0 @ 98)mars 31 18:29:35 genesyme-home gnome-shell[4738]: #23 5577a38c6aa8 iresource:///org/gnome/shell/ui/environment.js:221 (3cdb913cc830 @ 14)It seems to appear when the computer goes to sleep. Le mardi 29 mars 2022 à 10:28 -0700, 2nv2u a écrit :> Sorry for the late response, I cannot seem to reproduce this, are you> doing something specific or does it just happen?> —> Reply to this email directly, view it on GitHub, or unsubscribe.> You are receiving this because you authored the thread.Message ID:> <2nv2u/gnome-shell-extension-syncthing-> indicator/issues/12/ ***@***.*** >Message ID: ***@***.***>

**Comment by PhilippeRo** [comment]
I tried several things to give you more info but I can't reproduce the problem reliably. The only things I can tell you are:
- it happens when the computer goes to sleep; there is no screen locking (I disabled it);
- it only happens when the computer goes to sleep on its own (when I force it, there is no error);
I'm using f36 (but I had those messages in f35 as well).

**Comment by 2nv2u** [comment]
I'll try if I can reproduce it again using your hints, I'll come back to you asap!

**Comment by 2nv2u** [comment]
I can't seem to reproduce this, I'm sorry, from your log it looks something goes wrong in cleaning up the extension, but can't tell if this is just mine or all of them which might indicate something wrong in gnome shell itself.

**Comment by real-or-random** [comment]
I see those messages, too.
