### ISSUE TITLE
Error with paused folders

### ISSUE THREAD

**Issue by dr4Ke** [2nv2u/gnome-shell-extension-syncthing-indicator#14]
With paused folders, I have an error every time the extension checks its status (I guess):
```
[syncthing-indicator-manager:ERROR], Not Found, GET:/rest/db/completion, 404, folder is paused
```

I suppose that we could skip paused folders.

I may be able to do some more debugging if needed.

**Comment by 2nv2u** [comment]
I'll look into it and let you know if I need some more info, thanks!
