### ISSUE TITLE
"Connecting to 'device-id'..." error messages being thrown endlessly

### ISSUE THREAD

**Issue by seldon1000** [2nv2u/gnome-shell-extension-syncthing-indicator#2]
Hi, first I want to thank you for this extension. However, there seem to be a bug that is driving me crazy. I use Syncthing to sync one folder between my desktop and my smartphone, so the service is always running is background at boot time on both devices. Things work just fine at first, but at some point (and this happens all the time) the extension on my desktop goes crazy: it starts bombing me with tons of notifications nonstop saying there's a connection error to my smartphone. Screenshot below, full message is something like "Syncthing indicator service error, Connecting to 'device-id'...".

![photo_2021-03-02_10-11-25](https://user-images.githubusercontent.com/55358113/109625459-a8cb8b80-7b3f-11eb-8786-680502cf9638.jpg)

Syncthing service keeps working fine, Web UI also opens without errors, but I have to restart the service in order to stop the notifications.

I can't exactly tell what is causing this. It appears to be due to my smartphone disconnecting from WiFi and then reconnecting immediately after (bad signal) but I can't be sure. Regardless of the cause, the extension shouldn't bomb me with error messages for no reason.

**Comment by 2nv2u** [comment]
I'll look into it and see when this message is being created and how I can suppress it (reset the state).
I'm on it! :)

**Comment by 2nv2u** [comment]
Side note: I would also suggest creating a bug at the syncthing project, the message you see comes out of the error state of the daemon, so there is something going wrong. The only thing I can do is suppress it so it will only show up once.

**Comment by seldon1000** [comment]
Thank you.

> Side note: I would also suggest creating a bug at the syncthing project, the message you see comes out of the error state of the daemon, so there is something going wrong. The only thing I can do is suppress it so it will only show up once.

I actually thought about doing so, but I had used syncthing-gtk for months before switching to your extension and, even though it wasn't the best experience, I had never encountered a bug like this.
Also, while the error messages keep coming, Syncthing keeps working fine: the Web UI says that my smartphone is connected as expected and sync works too. 

I'll wait to hear some details from you.

**Comment by 2nv2u** [comment]
I fixed the flooding issue, the message should only show up once, I cannot do anything about the message itself however, that is something you have to file at the syncthing project itself.
Good luck!

**Comment by seldon1000** [comment]
That's great, thank you!
