### ISSUE TITLE
Error: Cannot find Syncthing config

### ISSUE THREAD

**Issue by Cutuchiqueno** [2nv2u/gnome-shell-extension-syncthing-indicator#20]
Since updgrade from PopOS 21.10 to 22.04 with Gnome 42 I get the following error message

![Screenshot from 2022-04-29 22-41-03](https://user-images.githubusercontent.com/306064/166066735-2cd58a10-a156-4c15-80e5-1762f0a59afd.png)

I removed and reinstalled the extionsion, rebootet the system, restart syncthing. Nothing solved it.

Where do I find the extension log?

**Comment by 2nv2u** [comment]
It's logging in the normal syslog, you might some more info there.
Can you also have a look at this ticket and show me your results?
https://github.com/2nv2u/gnome-shell-extension-syncthing-indicator/issues/19

I'll add as fallback the reading of the config file from the home folder of the current user in case the "syncthing --paths" command doesn't work.

**Comment by Cutuchiqueno** [comment]
It appears that it relates to `syncthing` itself, or better, the fact that I installed syncthing with `flatpak`. The output of ` flatpak run me.kozec.syncthingtk --paths` is:

    Gtk-Message: 12:00:20.312: Failed to load module "xapp-gtk3-module"
    Gtk-Message: 12:00:20.313: Failed to load module "appmenu-gtk-module"

So something does not work on this part, I suppose

**Comment by 2nv2u** [comment]
Yes, that does seem to be failing at your end, I'll still however use the fallback of the default config file location, I already committed it here in the repo and it will in the next release:

> I'll add as fallback the reading of the config file from the home folder of the current user in case the "syncthing --paths" command doesn't work.
