### ISSUE TITLE
installation fails 42.2

### ISSUE THREAD

**Issue by rubydesign** [2nv2u/gnome-shell-extension-syncthing-indicator#21]
This has worked great for me for a good while now, so thanks,
Now i am fully upgraded to 
fedora 36
 5.17.13-300.fc36.x86_64 
gnome 42.2
anything else?

Update from the gnome extension site fails and leaves the system in error state.
Bit of a shame as it was working before (fedora 35)

Did the git clone and install and that works. That's the only reason i add the issue, seems strange that git works when web install does not.

Any logs needed i can provide, just don't know which now.
Anyway, thanks

**Comment by 2nv2u** [comment]
Hi, it's pretty hard to tell why the install from the gnome extension site did not work, maybe you can find something in syslog?
Did you try removing it and adding it again?

**Comment by 2nv2u** [comment]
Since I haven't heard anything back I assume it's not an issue anymore, closing this ticket
