### ISSUE TITLE
Gnome 42.4 this._httpSession.queue_message is not a function

### ISSUE THREAD

**Issue by Retroman445** [2nv2u/gnome-shell-extension-syncthing-indicator#22]
Seems to be starting Syncthing, can access the dropdown menu, however updates of the icon do not occur.
I get this errormessage: this._httpSession.queue_message is not a function

![image](https://user-images.githubusercontent.com/51086501/190565851-bc3970e2-5216-4a2d-a4be-594e4f8d39dd.png)

**Comment by galen1423** [comment]
Same thing with Gnome 43...

**Comment by 2nv2u** [comment]
Should be fixed now, sorry for the delay

**Comment by galen1423** [comment]
I can confirm that works as expected for Ubuntu 22.10 with G.S 43. Thank you @2nv2u.
