### ISSUE TITLE
 Can you test it (gnome 43)

### ISSUE THREAD

**Issue by BirdInFire** [2nv2u/gnome-shell-extension-syncthing-indicator#23]
Hello do you think it's possible to test it (and enable support) for gnome 43 beta (fedora user will need it soon)).

**Comment by howyay** [comment]
I updated to Gnome 43 yesterday, current extension doesn't work out of the box, `Soup.Session.queue_message()` seemed to be deprecated in libsoup 3.0.

**Comment by 2nv2u** [comment]
Should be fixed now, sorry for the delay
