### ISSUE TITLE
Gnome 42.4 Error: Object 0x25caec0a3430 is not a subclass of GObject_Object, it's a Promise

### ISSUE THREAD

**Issue by rubberbander** [2nv2u/gnome-shell-extension-syncthing-indicator#24]
OS: Fedora Linux 36 (Workstation Edition)
Gnome Version: 42.4
Windowing System: Wayland

The Syncthing Indicator extension is broken. The extension loads successfully and I can see the icon on the top bar, but nothing works. The extension does not connect to the Syncthing service although it does successfully starts the service (I can see it running in the System Monitor). It does not show any of the connected devices or synced folders.

In the Extensions application, the extension is shown as not enabled (even though it is) and the following error message is shown:

> Object 0x25caec0a3430 is not a subclass of GObject_Object, it's a Promise

![Screenshot from 2022-09-27 13-14-01](https://user-images.githubusercontent.com/74119438/192605904-cd1f9ff6-c060-41a7-a073-f6d3bf8c22c4.png)

**Comment by aguillotc** [comment]
@rubberbander 

Are you using  https://extensions.gnome.org/extension/615/appindicator-support/ too ?

I had the exact same issue as you for days.
Just today, I just updated this other etxension through my regular update routine, and now just after a reboot of Gnome (Alt+F2, type `r`, then enter) the syncthing extension works again.

**Comment by miadabdi** [comment]
@aguillotc 
I can confirm it is caused by version 46 of app-indecator extension.
downgrading to 45 fixed the problem

**Comment by rubberbander** [comment]
@miadabdi
All Gnome extensions update automatically. I don't think there's a way to disable that.

**Comment by aguillotc** [comment]
You can install a Gnome extension manually, to avoid the problem of auto-update, I think.

The process is not complicated at all, you just have to do some manual work as depicted in this example article I took randomly on Internet : [Manual Installation of GNOME Extension from ZIP File [Easy Steps]](https://www.debugpoint.com/manual-installation-gnome-extension/).

**Comment by miadabdi** [comment]
Still no solution? (besides downgrading app-indecator)

**Comment by Havard-SL** [comment]
I managed to solve it by removing the "AppIndicator and KStatusNotifierItem Support" extension from extensions, and rather downloading it through the terminal with "sudo dnf install gnome-shell-extension-appindicator".

Turns out I already had gnome-shell-extension-appindicator installed on my system, maybe that caused the issue?

Thanks to AsciiWolf on the gnome extensions website for writing about the dnf package!
https://extensions.gnome.org/extension/615/appindicator-support/

**Comment by frost19k** [comment]
@Havard-SL 

> I managed to solve it by removing the "AppIndicator and KStatusNotifierItem Support" extension from extensions

I don't understand what you mean by this. `Gnome Extensions` app does not allow you to "add/install" or "remove/uninstall" extensions - just "activate/deactivate" them.

> Turns out I already had gnome-shell-extension-appindicator installed on my system

"AppIndicator and KStatusNotifierItem Support" & `gnome-shell-extension-appindicator` are the same thing.

Could you please paste the output of the following command?
`dnf info gnome-shell-extension-appindicator`

**Comment by 2nv2u** [comment]
I'm not sure what to do about this, any suggestions?
