### ISSUE TITLE
Socket I/O timed out

### ISSUE THREAD

**Issue by danth** [2nv2u/gnome-shell-extension-syncthing-indicator#25]
I'm running this on NixOS, where Syncthing is installed as a system service.

The indicator loads the initial state but does not refresh after that.

I'm seeing this error in the logs.

```
JS ERROR: Gio.IOErrorEnum: Socket I/O timed out
openConnectionMessage/<@/run/current-system/sw/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/syncthing.js:804:26
```

Do you have any ideas what could be causing this?

**Comment by 2nv2u** [comment]
It seems the URL of the API  isn't located / reachable at the location as specified in the config.
I cannot tell you why this is the case though, not enough information to go by and unfortunately I lack the time to test it on NixOS myself.

**Comment by 2nv2u** [comment]
Should be fixed now, was a bug shifting from libsoup 2 to 3
