### ISSUE TITLE
Syncthing Indicator causing 100% CPU usage and gnome-shell errors

### ISSUE THREAD

**Issue by kdkasad** [2nv2u/gnome-shell-extension-syncthing-indicator#26]
I originally reported this as an issue to GNOME Shell, but it turns out it's caused by the Syncthing Indicator extension:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6071

Essentially, when the Syncthing Indicator extension is enabled and Syncthing is running, the `gnome-shell` process throws constant errors and uses 100% CPU on one core.

It's caused by libsoup errors. A GNOME Shell developer said the following, which might be helpful:
> I had a quick look at the extension source code and it seems like it has not been adapted to this change between soup2 and soup3: https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html#status-codes-no-longer-used-for-internal-errors in openConnectionMessage. Since this has some code that could potentially end up creating lots of timeout sources, this might be what's causing the problem.

**Comment by 2nv2u** [comment]
Sorry for the delay, been very busy lately, I'll have a look and fix it asap.
Thanks for debugging this issue!

**Comment by 2nv2u** [comment]
Should be fixed, now using the gio error to detect time outs, please let me know if it's solved now
