### ISSUE TITLE
Impossible to install the extension in gnome-shell. Zombie extension?

### ISSUE THREAD

**Issue by Hypher** [2nv2u/gnome-shell-extension-syncthing-indicator#30]
GNOME Shell 42.5
Ubuntu 22.04.2 LTS

I installed the extension using the provided script install.sh
But it failed with `Extension “syncthing@gnome.2nv2u.com” does not exist`
So I retried manually: 

```bash
$ gnome-extensions install syncthing@gnome.2nv2u.com.zip
syncthing@gnome.2nv2u.com exists and --force was not specified
$ gnome-extensions enable syncthing@gnome.2nv2u.com
Extension “syncthing@gnome.2nv2u.com” does not exist
$ gnome-extensions list 
GPaste@gnome-shell-extensions.gnome.org
ding@rastersoft.com
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com
```

How is that even possible?
The extension exists but it does not exist?

I may be a gnome-shell bug, but since they have 4000+ open bugs, including segfaults, I doubt this bug - that may be only related to this extension - deserves a bug there.

**Comment by 2nv2u** [comment]
I think you're right, I cannot think of any reason why this extension itself is causing this
