### ISSUE TITLE
Syncthing daemon cannot be started, check log for more details

### ISSUE THREAD

**Issue by tuxedotje** [2nv2u/gnome-shell-extension-syncthing-indicator#32]
Syncthing daemon cannot be started, check log for more details. 
[@X ~]$ journalctl | syncthing
[start] 2023/08/25 14:13:36 INFO: syncthing v1.23.6 "Fermium Flea" (go1.20.5 linux-amd64) mockbuild@fedora-koji 2023-07-07 00:00:00 UTC
[start] 2023/08/25 14:13:36 WARNING: Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)
[monitor] 2023/08/25 14:13:36 INFO: Syncthing exited: exit status 1
[start] 2023/08/25 14:13:37 INFO: syncthing v1.23.6 "Fermium Flea" (go1.20.5 linux-amd64) mockbuild@fedora-koji 2023-07-07 00:00:00 UTC
[start] 2023/08/25 14:13:37 WARNING: Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)
[monitor] 2023/08/25 14:13:37 INFO: Syncthing exited: exit status 1
[start] 2023/08/25 14:13:38 INFO: syncthing v1.23.6 "Fermium Flea" (go1.20.5 linux-amd64) mockbuild@fedora-koji 2023-07-07 00:00:00 UTC
[start] 2023/08/25 14:13:38 WARNING: Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)
[monitor] 2023/08/25 14:13:38 INFO: Syncthing exited: exit status 1
[start] 2023/08/25 14:13:39 INFO: syncthing v1.23.6 "Fermium Flea" (go1.20.5 linux-amd64) mockbuild@fedora-koji 2023-07-07 00:00:00 UTC
[start] 2023/08/25 14:13:39 WARNING: Error opening database: resource temporarily unavailable (is another instance of Syncthing running?)
[monitor] 2023/08/25 14:13:39 INFO: Syncthing exited: exit status 1
[monitor] 2023/08/25 14:13:40 WARNING: 4 restarts in 4.062420656s; not retrying further

error message does not appear when gnome shell syncthing indicator is closed.

**Comment by 2nv2u** [comment]
I assume you run syncthing yourself outside of systemd, this extension tries to run syncthing with systemd and that might clash with you trying to run it in some other way.

**Comment by Skivling** [comment]
Ideally the extension should still provide it's additional functionality and just stop trying to start the daemon if it's already started by something else
