### ISSUE TITLE
Port to GNOME 45

### ISSUE THREAD

**Issue by gregorydk** [2nv2u/gnome-shell-extension-syncthing-indicator#33]
With GNOME Shell 45 all extensions will break and will need to be ported.

https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by 2nv2u** [comment]
Fixed pushed, enjoy! :)

**Comment by galen1423** [comment]
Thanks for updating your work. I'm testing this new version and for now, all seems good. We just have to hope that it passes the EGO test.

Regards
