### ISSUE TITLE
No connection on Arch-based GNOME 45 

### ISSUE THREAD

**Issue by salvoc81** [2nv2u/gnome-shell-extension-syncthing-indicator#34]
First of all, let me thank you for making this extension.

I tried to use it on two different machines with GNOME 45 (Manjaro and EndeavourOS), but did not work in both.  
Not sure what is the problem but it simply would not connect to synchthing.
Hope I can get some help...

Using syncthingtray until it is not fixed.

Thanks again, cheers

**Comment by 2nv2u** [comment]
I'm not sure what might be the issue, it seems that they both use systemd but it might not detect (or have a different name), perhaps even the config is not in the default ~/.config/syncthing folder.
As for the service itself, try this and see if it returns anything:

systemctl --user list-units syncthing.service
systemctl list-units syncthing.service

**Comment by tobehn** [comment]
I also cannot get a connection even though syncthing is running as a service.
Formerly, when enabling the service it was just
`systemctl enable syncthing.service`

Nowadays it's
`sysytemctl enable syncthing@<myuser>.service`
https://docs.syncthing.net/users/autostart.html#linux

Is the non-functioning connection perhaps due to this?

**Comment by tobehn** [comment]
I could get the indicator working by manually changing the extensions code to the correct service name.
https://github.com/2nv2u/gnome-shell-extension-syncthing-indicator/blob/fe58a1a3ea9a9c278c83b31c22f8bcead16e6e95/src/syncthing.js#L32 
This is of course no longterm solution.
I guess the syncthing.js needs to be edited to look for services called 

_syncthing.service_ and _syncthing@<myuser>.service_

**Comment by 2nv2u** [comment]
Changed and will check for system service first, this will disable the buttons since you can't start or stop system services as user.
