### ISSUE TITLE
On OpenSuse Tumbleweed - Continious message "connection-error"

### ISSUE THREAD

**Issue by ajvp-mozoilo** [2nv2u/gnome-shell-extension-syncthing-indicator#35]
Sincthyng works perfectly.
Slices "start from boot" and "service" work.
Connection to web interface opens fine.

What is not working is:
1st. Hostname device detection. It says just "This-device".
2nd. Folders shared detection. After remove default one I cannot  set nor make them detected. I mean, after log-out/log-in or reboot.
3rd. Probrably "rescan" should make second point work but no effect detected after click on it.

Thanks

**Comment by 2nv2u** [comment]
Gnome 46 support is added now, please be sure you installed it using systemd, any other way of running the daemon will result in unpredictable behavior, I might harden the extension in the future and add more unhappy path cases with proper error messages

**Comment by 2nv2u** [comment]
Will close this now since it's unclear what's boken
