### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by vinylSummer** [2nv2u/gnome-shell-extension-syncthing-indicator#36]
### Describe the bug

With the update of the gnome-shell the extension broke. Here are the changes: https://gjs.guide/extensions/upgrading/gnome-shell-46.html , I think that the relevant section is https://gjs.guide/extensions/upgrading/gnome-shell-46.html#gjs
The error: TypeError: this.add_actor is not a function

### Syncthing Indicator version

34
### Installed from

GNOME Extensions website
### GNOME Shell version

46
### Linux distribution/release

Arch Linux

**Comment by mschout** [comment]
I made a PR that fixes it for me on Gnome 46.

**Comment by 2nv2u** [comment]
> I made a PR that fixes it for me on Gnome 46.

Done, used your reference but removed the unnecessary check, thanks for your help though!

**Comment by StorageB** [comment]
I did a fresh install of Ubuntu 24.04 (Gnome 46) and the extension is not working.
Error: Unrecognized parameter "append_to"

![Screenshot from 2024-04-27 08-03-41](https://github.com/2nv2u/gnome-shell-extension-syncthing-indicator/assets/44729718/73f3d427-931b-42f6-8adb-ffe1c4d8b974)

**Comment by 2nv2u** [comment]
Hi, this issue must be happening in the gnome shell animation library that Ubuntu packages, "append_to" does not exist in the source code of the extension nor in the upstream animation code.
I'm running Fedora with Gnome 46 and it works fine, so I'm not sure where it comes from.

https://github.com/2nv2u/gnome-shell-extension-syncthing-indicator/blob/fe58a1a3ea9a9c278c83b31c22f8bcead16e6e95/src/extension.js#L32C1-L34C5

https://github.com/GNOME/gnome-shell/blob/aa51d56fa238a843682e5d2ea72a69401e5639fb/js/ui/animation.js#L20C1-L22C12

https://github.com/GNOME/gnome-shell/blob/aa51d56fa238a843682e5d2ea72a69401e5639fb/js/misc/params.js#L24C1-L24C69

**Comment by mschout** [comment]
I'm using Arch FWIW.  It works on Arch.
