### ISSUE TITLE
Change the green checkmark colour to be more visible

### ISSUE THREAD

**Issue by nourkagha** [2nv2u/gnome-shell-extension-syncthing-indicator#4]
Currently it's difficult to see in both light and dark modes.

Light mode:
![image](https://user-images.githubusercontent.com/50773468/114960466-c5adeb00-9e6f-11eb-9201-65a2901ee944.png)

Dark mode:
![image](https://user-images.githubusercontent.com/50773468/114960567-fa21a700-9e6f-11eb-8de0-b570ef20a5cf.png)

Suggestion: Use bright green for dark mode and dark green for light mode, or one shade that remains clearly visible in both modes.

**Comment by 2nv2u** [comment]
The idea was to make the arrow slightly visible, all other states are more pronounced, but I'll see if I can make it a little less.
I'll keep you posted!

**Comment by nourkagha** [comment]
Thanks! I thought that might be the intention, but indeed it's very easy to miss and not notice. Can do with a little extra visibility but without being overly bright and pronounced :)

**Comment by 2nv2u** [comment]
I made the icon a little more apparent, hope it's enough
