### ISSUE TITLE
Gnome Extensions keeps downgrading syncthing-indicator

### ISSUE THREAD

**Issue by seldon1000** [2nv2u/gnome-shell-extension-syncthing-indicator#5]
Gnome Extensions keeps downgrading syncthing-indicator to version 17. I tried installing versions 18 and 19 from GitHub but the extension is downgraded automatically immediately after. If I try to install it from gnome's website it just says that it's incompatible. Could it be syncthing-indicator's fault?

Arch Linux
GNOME 40.1

**Comment by 2nv2u** [comment]
Yes, there was a problem with older versions which I asked the EGO team to fix, but they haven't still.
I just bumped the version to overcome this issue, should be fixed when the new release has been accepted.
