### ISSUE TITLE
Gnome screen message : Update Syncthing Indicator  But 

### ISSUE THREAD

**Issue by tuxedotje** [2nv2u/gnome-shell-extension-syncthing-indicator#6]
In https://extensions.gnome.org/local/ no sign to update. (green square).
expected a green square button to upgrade. 
find no upgrade button.
Thanks for your extension.

**Comment by 2nv2u** [comment]
Hi, unfortunately I don't know what goes there, that's not something I can do anything about.
I would suggest removing and re-adding the plugin.
