### ISSUE TITLE
Disabled on GNOME 41

### ISSUE THREAD

**Issue by dcarosone** [2nv2u/gnome-shell-extension-syncthing-indicator#8]
This extension doesn't work any more on GNOME 41 (NixOS-unstable), it's disabled itself because of missing metadata.

![image](https://user-images.githubusercontent.com/11495017/139564354-3f4723af-a27d-4d29-bb7e-ece5a7060f29.png)

I assume it's as simple as adding the version to `src/metadata.json`

**Comment by 2nv2u** [comment]
You're right it isn't tested yet for 41, I haven't gotten to it yet.
If you however can alter the metadata.json and add version 41 to see if it works, I'll happily update the plugin before I have time to setup a VM to do so.

**Comment by eladyn** [comment]
I just tried it with altered metadata (gnome-unstable on archlinux) and it seems to work perfectly fine:
![syncthing-indicator-41](https://user-images.githubusercontent.com/59307989/140043004-da4366fe-6ffe-4494-afc3-79d222ad5f4b.png)

**Comment by dcarosone** [comment]
*gentle poke*

**Comment by 2nv2u** [comment]
Sorry for the delay, I updated the code, made a new release and uploaded it to EGO
