### ISSUE TITLE
Add support for localization

### ISSUE THREAD

**Issue by gyuris** [2nv2u/gnome-shell-extension-syncthing-indicator#9]
How to translate this extension? Please add support for localization.
 
I would like to create the Hungarian translation.

**Comment by 2nv2u** [comment]
Unfortunately it doesn't support localization (yet).
I will however add this when I have some time to spare.
Stay tuned!

**Comment by 2nv2u** [comment]
I added the possibility to add translations, if you can supply the hungarian po file in the po folder, I'll add it to the release
